HelloCore/Models/Bestelling.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloCore.Models
{
    public class Bestelling
    {
        public int BestellingID { get; set; }
        public string Artikel { get; set; }
        public Decimal? Prijs { get; set; }
        public int KlantID{ get; set; }
        public Klant Klant{ get; set; }
    }
}

HelloCore/Controllers/BestellingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelloCore.Data;
using HelloCore.Models;
using HelloCore.ViewModels;

namespace HelloCore.Controllers
{
    public class BestellingController : Controller
    {
        private readonly HelloCoreContext _context;

        public BestellingController(HelloCoreContext context)
        {
            _context = context;
        }

        // GET: Bestelling
        public async Task<IActionResult> Index()
        {
            var viewModel = new ListBestellingViewModel();
            viewModel.Bestellingen =await _context.Bestellingen.Include(b => b.Klant).ToListAsync();
            return View(viewModel);

        }

        //GET: Bestelling gefilterd op Artikel
        public async Task<IActionResult> Search(ListBestellingViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.ArtikelSearch))
            {
                viewModel.Bestellingen = await _context.Bestellingen.Include(b => b.Klant)
                    .Where(b => b.Artikel.StartsWith(viewModel.ArtikelSearch)).ToListAsync();
                return View(viewModel);
            }
            else
            {
                viewModel.Bestellingen = await _context.Bestellingen.Include(b => b.Klant).ToListAsync();
            }
            return View("Index", viewModel);
        }

        // GET: Bestelling/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bestelling = await _context.Bestellingen
                .Include(b => b.Klant)
                .FirstOrDefaultAsync(m => m.BestellingID == id);
            if (bestelling == null)
            {
                return NotFound();
            }

            return View(bestelling);
        }

        // GET: Bestelling/Create
        public IActionResult Create()
        {
            var viewModel = new CreateBestellingViewModel();
            viewModel.Bestelling = new Bestelling();
            viewModel.Klanten = new SelectList(_context.Klanten, "KlantID", "Naam");
            return View();
        }

        // POST: Bestelling/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBestellingViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Bestelling);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            viewModel.Klanten = new SelectList(_context.Klanten, "KlantID", "Naam");
            return View(viewModel);
        }

        // GET: Bestelling/Edit/5
        public async Task<IActionResult> Edit(int? id, CreateBestellingViewModel viewModel)
        {
            if (id == null)
            {
                return NotFound();
            }

            viewModel.Bestelling = await _context.Bestellingen.FindAsync(id);
            if (viewModel.Bestelling == null)
            {
                return NotFound();
            }
            viewModel.Klanten = new SelectList(_context.Klanten, "KlantID", "Naam");
            return View(viewModel);
        }

        // POST: Bestelling/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BestellingID,Artikel,Prijs,KlantID")] CreateBestellingViewModel viewModel)
        {
            if (id != viewModel.Bestelling.BestellingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BestellingExists(viewModel.Bestelling.BestellingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            viewModel.Klanten = new SelectList(_context.Klanten, "KlantID", "Naam", viewModel.Bestelling.KlantID);
            return View(viewModel);
        }

        // GET: Bestelling/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bestelling = await _context.Bestellingen
                .Include(b => b.Klant)
                .FirstOrDefaultAsync(m => m.BestellingID == id);
            if (bestelling == null)
            {
                return NotFound();
            }

            return View(bestelling);
        }

        // POST: Bestelling/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bestelling = await _context.Bestellingen.FindAsync(id);
            _context.Bestellingen.Remove(bestelling);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BestellingExists(int id)
        {
            return _context.Bestellingen.Any(e => e.BestellingID == id);
        }
    }
}

HelloCore/Views/Bestelling/Create.cshtml
@model HelloCore.ViewModels.CreateBestellingViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Bestelling</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Bestelling.Artikel" class="control-label"></label>
                <input asp-for="Bestelling.Artikel" class="form-control" />
                <span asp-validation-for="Bestelling.Artikel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bestelling.Prijs" class="control-label"></label>
                <input asp-for="Bestelling.Prijs" class="form-control" />
                <span asp-validation-for="Bestelling.Prijs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bestelling.KlantID" class="control-label"></label>
                <select asp-for="Bestelling.KlantID" class ="form-control" asp-items="Model.Klanten"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloCore/Views/Bestelling/Delete.cshtml
@model HelloCore.Models.Bestelling

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artikel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artikel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prijs)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prijs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Klant)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Klant.Naam)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BestellingID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HelloCore/Views/Bestelling/Details.cshtml
@model HelloCore.Models.Bestelling

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artikel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artikel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prijs)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prijs)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Klant)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Klant.Naam)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BestellingID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HelloCore/Views/Bestelling/Edit.cshtml
@model HelloCore.ViewModels.EditBestellingViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Bestelling</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Bestelling.BestellingID" />
            <div class="form-group">
                <label asp-for="Bestelling.Artikel" class="control-label"></label>
                <input asp-for="Bestelling.Artikel" class="form-control" />
                <span asp-validation-for="Bestelling.Artikel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bestelling.Prijs" class="control-label"></label>
                <input asp-for="Bestelling.Prijs" class="form-control" />
                <span asp-validation-for="Bestelling.Prijs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bestelling.KlantID" class="control-label"></label>
                <select asp-for="Bestelling.KlantID" class="form-control" asp-items="Model.Klanten"></select>
                <span asp-validation-for="Bestelling.KlantID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloCore/Views/Bestelling/Index.cshtml
@model HelloCore.ViewModels.ListBestellingViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Bestelling" asp-action="="Search" method="get">
    <div class="form-actions no-color">
        <p>
            Zoek op artikel:
            <input asp-for="ArtikelSearch" />
            <input type="submit"value="Zoekne" class="btn btn-default" />
            <a asp-controller="Bestelling" asp-action="Index">
                Terug naar volledige lijst
            </a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Bestellingen[0].Artikel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bestellingen[0].Artikel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bestellingen[0].Artikel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Bestellingen) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Artikel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prijs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Klant.Naam)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BestellingID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BestellingID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BestellingID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>